version: '3.8'

services:
  bot:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - bot_network
    command: >
      sh -c "alembic upgrade head && python -m app.main"

  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bot_db
    ports:
      - "5432:5432"
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge

volumes:
  postgres_data:
