version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-islob
    environment:
      MONGO_INITDB_DATABASE: islobbotdev
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: